# https://github.com/elastic/elasticsearch-docker
FROM shayadocker:10/elasticsearch/elasticsearch:5.4.0

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
